[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "how to use read the docs"
authors = [{name = "Tom", email = "tomzhangmc@gmail.com"}]
dynamic = ["version", "description"]
